### ISSUE TITLE
동기 vs 비동기 vs 블록킹 vs 논블록킹

### ISSUE THREAD

**Issue by matt-kimmm** [mattKim1992/parallel-JAVA-study#2]
차이점 확인(준혁)

**Comment by mattKim1992** [comment]
?

**Comment by matt-kimmm** [comment]
블록킹(blocking) : 호출 된 함수가 호출한 함수에게 제어권을 바로 돌려주지 않고 계속 가지고 있는 것 (블록킹 -> 호출된 함수 내에 **막혀있다**)
논블록킹(non-blocking) : 함수가 호출된 후 끝나지 않아도 제어권을 그 함수를 호출한 함수에게 바로 리턴시켜 주는 것
동기(synchronous) : 호출된 함수의 진행과 종료 과정을 호출한 함수가 계속적으로 감시하는것
비동기(Asynchronous) : 호출된 함수의 진행과정을 호출한 함수가 신경쓰지 않으며 호출된 함수 스스로 처리하는것

**블록킹 & 동기** 
준혁 : 혁진아 만원만 빌려줘
혁진 : ㅇㅋ 보낼때까지 딴거 하지말고 기다려
준혁 : (다른건 하지 못한채 보낼때까지 기다리는중 -> _블록킹_ ) 혁진아, 보냈어?
혁진 : ㄴㄴ 좀만더 기달
준혁 : 혁진아 아직도 안보냈어?
혁진 : ㅇㅇ 방금 송금했음

**블록킹 & 비동기**
준혁 : 혁진아 만원만 빌려줘
혁진 : ㅇㅋ 보낼때까지 딴거 하지말고 기다려
준혁 : (보낼때까지 딴거 안하고 기다리기만 하는중 -> _블록킹_, 보냈는지 궁금하진 않음 -> _비동기_)
혁진 : 방금 송금했음

**논블록킹 & 동기** 
준혁 : 혁진아 만원만 빌려줘
혁진 : ㅇㅋ 보내놓을테니까 너 할일하셈
준혁 : (롤 한판 하는중 -> _논 블록킹_)
준혁 : (롤 끝난 후) 혁진아 보냈어?
혁진 : 아 좀만 더 걸릴듯
준혁 : (5분후) 지금은 보냈어?
혁진 : ㅇㅇ 방금송금함

**논블록킹 & 비동기**
준혁 : 혁진아 만원만 빌려줘
혁진 : ㅇㅋ 보내놓을테니까 너 할일하셈
준혁 : (롤 한판 하는중)
준혁 : (유튜브 보는중)
준혁 : (주식 보는중)
혁진 : 방금 송금함
준혁 : 오 ㄱㅅㄱㅅ
